name: Build-TestsUI-DeployAPP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Install playwright browsers
      run: npx playwright install
    - name: Replace config settings
      run: echo "export const settings = { host:\"http://localhost:3030\" };" > src/config.js
    - name: Start Backend
      run: npm run start-be & 
    - name: Sleep for 2 seconds
      run: sleep 2
    - name: Start FrontEnd
      run: npm run start-fe &
    - name: Sleep for 2 seconds
      run: sleep 2
    - name: Execute UI Tests
      run: npm run test-ui

  deploy-be:
    needs: build_and_test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_BE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}

  deploy-fe:
    needs: build_and_test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_FE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}