name: Build-TestsUI-DeployAPP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Install playwright browsers
      run: npx playwright install
    - name: Replace config settings
      run: echo "export const settings = { host:\"http://localhost:3030\" };" > src/config.js
    - name: Start Backend
      run: npm run start-be & 
    - name: Sleep for 2 seconds
      run: sleep 2
    - name: Start FrontEnd
      run: npm run start-fe &
    - name: Sleep for 2 seconds
      run: sleep 2
    - name: Execute UI Tests
      run: npm run test-ui

  deploy-be:
    needs: build_and_test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.SERVICE_BE_ID }}
          api_key: ${{ secrets.RENDER_TOKEN }}
          wait_deploy: true
            
  deploy-fe:
    needs: build_and_test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.SERVICE_FE_ID }}
            api_key: ${{ secrets.RENDER_TOKEN }}
            wait_deploy: true
